# @package _global_

# defaults:
#   - _self_
#   - data: radar
#   - module: rem
#   - trainer: default

experiment_name: test  #Override this
ROOT_DATA_PATH: '/home/colin/hdd/workspace/object2sphere/datasets'
RESULTS_PATH: '/home/colin/hdd/workspace/object2sphere/datasets/out'
batch_size: 4
num_workers: 12

train_dataset:
  _target_: o2s.datasets.radar_dataset.RadarDataset
  root: ${ROOT_DATA_PATH}/test_dataset.nc #TODO: add dataset name
  stage: train
  mesh_mode: simple
  orientation_mode: full 
  transform:
    _target_: o2s.datasets.transforms.general.Compose
    transforms:
      - _target_: o2s.datasets.transforms.radar.Normalize
        min: 0.0
        max: 1.0
      #- _target_: o2s.datasets.transforms.radar.Abs
      #- _target_: o2s.datasets.transforms.radar.Log
      #- _target_: o2s.datasets.transforms.radar.Center
      #  mean: -7.352605819702148 #TODO: Verify the values
      #  std: 2.067737340927124

val_dataset:
  _target_: o2s.datasets.radar_dataset.RadarDataset
  root: ${ROOT_DATA_PATH}/test_dataset.nc  #TODO: add dataset name
  stage: val
  mesh_mode: simple
  orientation_mode: full
  transform:
    _target_: o2s.datasets.transforms.general.Compose
    transforms:
      - _target_: o2s.datasets.transforms.radar.Normalize
        min: 0.0
        max: 1.0
      #- _target_: o2s.datasets.transforms.radar.Abs
      #- _target_: o2s.datasets.transforms.radar.Log
      #- _target_: o2s.datasets.transforms.radar.Center
      #  mean: -7.352605819702148 #TODO: Verify the values
      #  std: 2.067737340927124

test_dataset:
  _target_: o2s.datasets.radar_dataset.RadarDataset
  root: ${ROOT_DATA_PATH}/test_dataset.nc  #TODO: add dataset name
  stage: test
  mesh_mode: simple
  orientation_mode: full 
  transform:
    _target_: o2s.datasets.transforms.general.Compose
    transforms:
      - _target_: o2s.datasets.transforms.radar.Normalize
        min: 0.0
        max: 1.0
      #- _target_: o2s.datasets.transforms.radar.Abs
      #- _target_: o2s.datasets.transforms.radar.Log
      #- _target_: o2s.datasets.transforms.radar.Center
      #  mean: -7.352605819702148 #TODO: Verify the values
      #  std: 2.067737340927124
  

module:
  _target_: o2s.lightning.rem.REMLightningModule

  backbone: 
    _target_: o2s.models.object_2_sphere.Mesh2Sphere
    latent_lmax: 5
    output_lmax: 50
    latent_feat_dim: 128
    max_radius: 10.0
    num_out_spheres: 1
    use_mlp: False 

  criterion:
    _target_: o2s.lightning.rem.SoftmaxWeightedMSELoss
    reduction: sum

  optim:
    optimizer: 
      _target_: torch.optim.AdamW
      _partial_: True
      lr: 1e-4
      weight_decay: 1e-5
    lr_scheduler:
      _target_: torch.optim.lr_scheduler.StepLR
      _partial_: True
      gamma: 0.1
      step_size: 15

trainer:
  _target_: pytorch_lightning.trainer.Trainer

  devices: auto
  accelerator: cuda
  strategy: ddp
  num_nodes: 1
  max_epochs: 20
  gradient_clip_val: 0.5
  num_sanity_val_steps: 0
  logger:
    _target_: pytorch_lightning.loggers.MLFlowLogger
    experiment_name: ${experiment_name}
    run_name: ${experiment_name}/${now:%Y-%m-%d-%H-%M-%S}
    tracking_uri: ${RESULTS_PATH}/mlflow/
  callbacks:
    - _target_: pytorch_lightning.callbacks.ModelCheckpoint
      dirpath: "."
      filename: "model_{epoch}"
      monitor: "val/loss"
      save_last: True
    - _target_: pytorch_lightning.callbacks.LearningRateMonitor


hydra:
  run:
    dir: ${RESULTS_PATH}/hydra/${experiment_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
