# @package _global_

# defaults:
#   - _self_
#   - data: radar
#   - module: rem
#   - trainer: default

experiment_name: basic_asym 
#ROOT_DATA_PATH: '/home/gridsan/ckohler/workspace/object2sphere/datasets'
#RESULTS_PATH: '/home/gridsan/ckohler/workspace/object2sphere/datasets/out'
ROOT_DATA_PATH: '/home/colin/hdd/workspace/object2sphere/datasets'
RESULTS_PATH: '/home/colin/hdd/workspace/object2sphere/datasets/out'
batch_size: 64
num_workers: 12

train_dataset:
  _target_: o2s.datasets.radar_dataset.RadarDataset
  root: ${ROOT_DATA_PATH}/train_radar_0.nc 
  stage: train
  mesh_mode: simple
  orientation_mode: full 
  transform:
    _target_: o2s.datasets.transforms.general.Compose
    transforms:
      - _target_: o2s.datasets.transforms.radar.Abs
      - _target_: o2s.datasets.transforms.radar.Log
      - _target_: o2s.datasets.transforms.radar.Center
        mean: -3.5158
        std: 1.1688
        #mean: -8.102414
        #std: 2.7063365
        #- _target_: o2s.datasets.transforms.radar.Normalize
        #  #data_min: -1014.8423
        #  #data_max: 977.3337
        #  data_min: -31.385
        #  data_max: 6.923 
        #  target_min: -0.5
        #  target_max: 0.5

val_dataset:
  _target_: o2s.datasets.radar_dataset.RadarDataset
  root: ${ROOT_DATA_PATH}/test_radar.nc 
  stage: val
  mesh_mode: simple
  orientation_mode: full
  transform:
    _target_: o2s.datasets.transforms.general.Compose
    transforms:
      - _target_: o2s.datasets.transforms.radar.Abs
      - _target_: o2s.datasets.transforms.radar.Log
      - _target_: o2s.datasets.transforms.radar.Center
        mean: -3.5158
        std: 1.1688
          #mean: -8.102414
          #std: 2.7063365
          #- _target_: o2s.datasets.transforms.radar.Normalize
          #  #data_min: -943.4362
          #  #data_max: 979.1366
          #  data_min: -31.385
          #  data_max: 6.923
          #  target_min: -0.5
          #  target_max: 0.5

test_dataset:
  _target_: o2s.datasets.radar_dataset.RadarDataset
  root: ${ROOT_DATA_PATH}/test_radar.nc  
  stage: test
  mesh_mode: simple
  orientation_mode: full 
  transform:
    _target_: o2s.datasets.transforms.general.Compose
    transforms:
      - _target_: o2s.datasets.transforms.radar.Abs
      - _target_: o2s.datasets.transforms.radar.Log
      - _target_: o2s.datasets.transforms.radar.Center
        mean: -3.5158
        std: 1.1688
          #mean: -8.102414
          #std: 2.7063365
          #- _target_: o2s.datasets.transforms.radar.Normalize
          #  data_min: -31.385
          #  data_max: 6.923
          #  target_min: -0.5
          #  target_max: 0.5

module:
  _target_: o2s.lightning.rem.REMLightningModule

  backbone: 
    _target_: o2s.models.object_2_sphere.Mesh2Radar
    latent_lmax: 5
    output_lmax: 25
    latent_feat_dim: 128
    max_radius: 10.0
    num_out_spheres: 34 #67
    use_mlp: True
    num_layers_equivformer: 4
    num_heads_equivformer: 4
    num_theta: 61
    num_phi: 21

  criterion:
    _target_: o2s.lightning.rem.SoftmaxWeightedMSELoss
    reduction: sum

  optim:
    optimizer: 
      _target_: torch.optim.AdamW
      _partial_: True
      lr: 1e-4
      weight_decay: 1e-5
    lr_scheduler:
      _target_: torch.optim.lr_scheduler.StepLR
      _partial_: True
      gamma: 0.1
      step_size: 15

trainer:
  _target_: pytorch_lightning.trainer.Trainer

  devices: auto
  accelerator: cuda
  strategy: ddp
  num_nodes: 1
  max_epochs: 20
  gradient_clip_val: 0.5
  num_sanity_val_steps: 0
  logger:
    _target_: pytorch_lightning.loggers.MLFlowLogger
    experiment_name: ${experiment_name}
    run_name: ${experiment_name}/${now:%Y-%m-%d-%H-%M-%S}
    tracking_uri: ${RESULTS_PATH}/mlflow/
  callbacks:
    - _target_: pytorch_lightning.callbacks.ModelCheckpoint
      dirpath: "."
      filename: "model_{epoch}"
      monitor: "val/loss"
      save_last: True
    - _target_: pytorch_lightning.callbacks.LearningRateMonitor


hydra:
  run:
    dir: ${RESULTS_PATH}/hydra/${experiment_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
